from rtamt.operation.stl.discrete_time.online.cpp.ast_visitor import StlDiscreteTimeOnlineAstVisitorCpp
from rtamt.operation.abstract_discrete_time_online_interpreter import discrete_time_online_interpreter_factory

def StlDiscreteTimeOnlineInterpreterCpp():
    stlDiscreteTimeOnlineInterpreterCpp = discrete_time_online_interpreter_factory(StlDiscreteTimeOnlineAstVisitorCpp)()
    return stlDiscreteTimeOnlineInterpreterCpp
